// Copyright 2021 Christopher Sugai

//! Experimental character sets.
//! These character sets are generated by the qs_gen function in utils::function.
//! PHRED33 is encoded as ASCII 33-73, this includes some letters. We want to make a single characterset from the sequence and quality lines, but the sequence and quality possibilities overlap.
//! We multiply the characters by getting the phred33 and subtracting 33, meaning the phred integer is now from 0-40 shifting the ascii possibilities up 128 (so now 128-255) to avoid conflict with any ascii even if extended in the phred representation, and multiply them together.
//! We change u8 to u16 in the function as we exceed u8 values.

use bioutils::utils::function::qs_bytes;
use bioutils::utils::check::*;
fn main(){
    let mut x = b"TTTTAAAACCCCGGGG".to_vec();
    let mut y = b"!!@@!!@@!!@@!!@@".to_vec();
    println!("{:?}", qs_bytes(&mut x,&mut y));
    println!("{:?}", &x);
    println!("{:?}", &y);
    println!("{:?}", &y.is_iupac());
    println!("{:?}", &y.is_seq_qual_length_equal(&x));
}
// In this example, we read a gz fastq and write a qs file. The qs file can then be converted back to fastq with the qs_to_fastq function.
