// Copyright 2021 Christopher Sugai

//! Experimental character sets.
//! These character sets are generated by the qs_gen function in utils::function.
//! PHRED33 is encoded as ASCII 33-73, this includes some letters. 
//! This is done simply by getting the phred33, adding the ascii possibilities and subtracting 127 to start at 0. This means we subtract 160 total.
//! 52*128=6656 combinations, so we use a u16 and encode from 0 to 6655.

use bioutils::utils::function::qs_bytes;

fn main(){
    let mut x = b"TTTTAAAACCCCGGGG".to_vec();
    let mut y = b"!!@@!!@@!!@@!!@@".to_vec();
    println!("{:?}", qs_bytes(&mut x,&mut y));
    println!("{:?}", &x);
    println!("{:?}", &y);
}
